### ISSUE TITLE
crate fails to comile on 32-bit architectures

### ISSUE THREAD

**Issue by decathorpe** [paritytech/fdlimit#5]
Trying to build this crate on fedora fails on 32-bit architectures (armv7hl and i686) with this error:

```
   --> src/lib.rs:108:8
    |
108 |         Some(rlim.rlim_cur)
    |              ^^^^^^^^^^^^^
    |              |
    |              expected `u64`, found `u32`
    |              help: you can convert an `u32` to `u64`: `rlim.rlim_cur.into()`
```

This error (and that it only occurs on 32-bit architectures) makes me think that this is an instance of where using `usize` would be appropriate, since it's the architecture-dependent integer type (4 bytes ~ u32 on 32-bit architectures, and 8 bytes ~ u64 on 64-bit architectures, according to the [rust docs]).

[rust docs]: https://doc.rust-lang.org/std/primitive.usize.html

**Comment by NikVolf** [comment]
@mxinden care to fix?

**Comment by mxinden** [comment]
Interesting. I explicitly tested https://github.com/paritytech/fdlimit/pull/4 for 32bit, see description. I will take a deeper look. Thanks for reporting @decathorpe!

**Comment by mxinden** [comment]
@decathorpe let me know what you think of https://github.com/paritytech/fdlimit/pull/6.
